sudo: required
services:
  - docker 

before_install:
  - docker build -t wn0858/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wn0858/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker-react"
  env: "DockerReact-env"
  bucket_name:  "elasticbeanstalk-us-east-2-716105475783"
  # same a app name
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_Secret_Access_Key"



